//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Storage.Json.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movies.Storage.Json.Tests.Resources.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///      &quot;vote_count&quot;: 886,
        ///      &quot;id&quot;: 424783,
        ///      &quot;video&quot;: false,
        ///      &quot;vote_average&quot;: 6.5,
        ///      &quot;title&quot;: &quot;Bumblebee&quot;,
        ///      &quot;popularity&quot;: 413.643,
        ///      &quot;poster_path&quot;: &quot;/fw02ONlDhrYjTSZV8XO6hhU3ds3.jpg&quot;,
        ///      &quot;original_language&quot;: &quot;en&quot;,
        ///      &quot;original_title&quot;: &quot;Bumblebee&quot;,
        ///      &quot;genre_ids&quot;: [
        ///        28,
        ///        12,
        ///        878
        ///      ],
        ///      &quot;backdrop_path&quot;: &quot;/hMANgfPHR1tRObNp2oPiOi9mMlz.jpg&quot;,
        ///      &quot;adult&quot;: false,
        ///      &quot;overview&quot;: &quot;On the run in the year 1987, Bumblebee finds refuge in a jun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string movies {
            get {
                return ResourceManager.GetString("movies", resourceCulture);
            }
        }
    }
}
